### ISSUE TITLE
Error setting up Docker container

### ISSUE THREAD

**Issue by saatvikshah** [gf712/shogun-docker#1]
I have installed the latest docker on my Mac(10.14.2) and started the daemon.

I then tried running the script after installing the required dependencies to see the following output:
```
➜  shogun-docker git:(master) python3 cmake_configs.py config.yml --path ../shogun --result_path .
Building image (could take a while)...
Stopping and deleting docker container...
Could not stop and delete container.
404 Client Error: Not Found ("No such container: shogun-memory")
```
Am I missing some initial setup step?

**Comment by gf712** [comment]
ah, thanks for reporting that. It seems like I haven't done the pathing properly for `--result_path`. If you don't set ` --result_path` it will create everything in the current directory and runs fine. I'll try and fix it asap though!

**Comment by gf712** [comment]
It should work fine now!
